### ISSUE TITLE
Bootloop after Sd2vita to ux0 with 3.65 Enso

### ISSUE THREAD

**Issue by silverizer** [Applelo/SwitchSD2Vita#9] opened 2018-04-23 17:10 UTC
Hi i tried to use your app to simplify everything in terms of switching sd2vita to ux0 and uma0
however i get bootloop after reboot
I was able to boot again by holding Ltrigger Psbutton and Power

when i use this plugin it works to set my Sd2vita as umao
https://github.com/Ninoh-FOX/gamecard-microsd-uma0/releases
 
but id like to use my Sd2vita as ux0 and use my Original Sony Memory card as uma0
i hope you can look it up thank you and more power to you.

I am currently using 64gb original Sony memory card and I have a Samsung Evo plus 256gb microsd on sd2vita V3 adapter

**Comment by silverizer** [comment] 2018-04-23 18:31
oh nevermind i was able to firgure it out 😄

**Comment by silverizer** [comment] 2018-04-23 18:35
If its posssible for you to recompile your app using this plugins i would really appreciate it

**Comment by silverizer** [comment] 2018-04-23 18:36
[plugins.zip](https://github.com/Applelo/SwitchSD2Vita/files/1939562/plugins.zip)

**Comment by chrisdragonuk** [comment] 2018-05-01 05:33
how did u fix this i am getting the same thing

**Comment by Applelo** [comment] 2018-05-01 17:47
Hello, sorry for the delay to response. I'm busy by my studies... @silverizer test this and tell me if this vpk fix your issue.
[switch_sd2vita.vpk.zip](https://github.com/Applelo/SwitchSD2Vita/files/1964663/switch_sd2vita.vpk.zip)

@chrisdragonuk If you have bootloop, holding L trigger + PS Button and Power Button to disable plugin.

**Comment by ABDOULemul** [comment] 2018-07-02 17:35
This vpk don't work in h-encore 3.68.

**Comment by Applelo** [comment] 2018-07-02 17:40
@ABDOULemul I open a new issue. It's not the topic of this one ^^

**Comment by Applelo** [comment] 2018-07-02 17:55
I close the issue because I have no reply by @silverizer . I consider the problem is solved.

**Closed as completed by Applelo** 2018-07-02 17:55 UTC
